[mail function]
; For Unix only.  You may supply arguments as well (default: "sendmail -t -i").
; http://php.net/sendmail-path

; Use mailpit
; sendmail_path = "/usr/local/bin/mailpit sendmail"
sendmail_path = "/usr/local/bin/sendmail -S email:1025"
; Use mailhog for sending emails
; sendmail_path = "/usr/local/bin/mhsendmail --smtp-addr=mailhog:1025"