[xdebug]
; Mode will be read by the environment variable XDEBUG_MODE
; which is passed in by Docker via .env > compose.yml
; After changing in .env, restart the container to take effect.
; xdebug.mode = off
xdebug.start_with_request = yes
xdebug.client_host = host.docker.internal
xdebug.client_port = 9003
xdebug.idekey = VSCODE
; xdebug.log = /var/www/html/storage/logs/xdebug.log
; xdebug.log_level = 7